defaults: &defaults
  app_name: "Artstore"
  facebook_app_id: "517584478368151"
  facebook_secret: "58e61dd1cd1b7867cc5b31c39c413f1a"


development:
  <<: *defaults
  domain: "http://artstore.dev"

test:
  <<: *defaults

production:
  <<: *defaults